### ISSUE TITLE
 Binary XML file line #18: You must supply a layout_width attribute.

### ISSUE THREAD

**Issue by rachanon** [Karumi/ExpandableSelector#7]
Hi, I just copied from your instruction and then compiled. I've got some error message like this below 

Caused by: java.lang.UnsupportedOperationException: Binary XML file line #18: You must supply a layout_width attribute.
                                                                    at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:709)
                                                                    at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6889)
                                                                    at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7071)
                                                                    at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:446)
                                                                    at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:386)
                                                                    at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:385)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:502)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                    at com.karumi.expandableselector.ExpandableSelector.initializeButton(ExpandableSelector.java:277) 
                                                                    at com.karumi.expandableselector.ExpandableSelector.renderExpandableItems(ExpandableSelector.java:231) 
                                                                    at com.karumi.expandableselector.ExpandableSelector.showExpandableItems(ExpandableSelector.java:92) 
                                                                    at indie.kcalulator.ListsActivity.initializeSizesExpandableSelector(ListsActivity.java:84) 
                                                                    at indie.kcalulator.ListsActivity.onCreate(ListsActivity.java:69) 
                                                                    at android.app.Activity.performCreate(Activity.java:6237) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

Could you tell me how do I fix this because this error message told me that your code is not declare a layout_width attribute on android view. 

I suppose that tools:ignore="RequiredSize" in expandable_item_button layout doesn't work 

Thanks in advance.

**Comment by pedrovgs** [comment]
Hi @rachanon can you send us the layout file?

**Comment by rachanon** [comment]
Here is my layout file

[activity_lists.xml.zip](https://github.com/Karumi/ExpandableSelector/files/175605/activity_lists.xml.zip)

**Comment by pedrovgs** [comment]
Hi @rachanon!

I can't reproduce the bug in the sample project :S I have some questions:
- What's the target sdk, you are using?
- What's the build tools and compile sdk version you are using?
- Maybe the bug can be related with the root layout you are using? Can you check if this bug is reproducible using a relative layout instead of a percent relative layout?

**Comment by rachanon** [comment]
I use this version below
compileSdkVersion 23
buildToolsVersion "23.0.2"
minSdkVersion 19
targetSdkVersion 23

I've check this bug is reproduce when using a percent relative layout but relative layout is not.

**Comment by pedrovgs** [comment]
Cool thanks!

**Comment by JAED1990** [comment]
Hi, I just copied from your instruction and then compiled. I've got some error message like this below

java.lang.RuntimeException: Binary XML file line #18: You must supply a layout_width attribute.
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2205)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:142)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5118)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: java.lang.RuntimeException: Binary XML file line #18: You must supply a layout_width attribute.
                                                                                   at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
                                                                                   at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:5963)
                                                                                   at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6132)
                                                                                   at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:615)
                                                                                   at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:559)
                                                                                   at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:56)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:480)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                   at com.karumi.expandableselector.ExpandableSelector.initializeButton(ExpandableSelector.java:279)
                                                                                   at com.karumi.expandableselector.ExpandableSelector.renderExpandableItems(ExpandableSelector.java:231)
                                                                                   at com.karumi.expandableselector.ExpandableSelector.showExpandableItems(ExpandableSelector.java:92)
                                                                                   at com.dxtre.www.detallitossabores.MainActivity.onCreate(MainActivity.java:36)
                                                                                   at android.app.Activity.performCreate(Activity.java:5275)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:142) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5118) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606) 
                                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by pedrovgs** [comment]
Hi @rachanon!

I can't reproduce the bug in the sample project :S I have some questions:
Hi @JAED1990 I need more information to help you:
- What's the target sdk, you are using?
- What's the build tools and compile sdk version you are using?
- Maybe the bug can be related with the root layout you are using? Can you check if this bug is reproducible using a relative layout instead of a percent relative layout?

**Comment by tyisme614** [comment]
Hi,
I encountered the same problem as others mentioned up there. in my project. I followed the instructions that you wrote on your homepage. I'm using ViewPager, so that my expandable selector is used inside a fragment. I don't know if  your library is incompatible with Fragment. Could you give me some hints for solving this? 
info of my android studio
 compileSdkVersion 21
    buildToolsVersion "23.0.2"
minSdkVersion 18
        targetSdkVersion 21

**Comment by pedrovgs** [comment]
@tyisme614 can you create a project reproducing the bug? I'd like to fix it but I can't reproduce it :S

**Comment by tyisme614** [comment]
@pedrovgs Hi, I just figured it out. the reason why i encountered that problem is because the wrong style setting in androidmanifest.xml. The theme definition of my application didn't include the style called ExpandableItemStyle which is used in your sample.

This is how i figured it out. I just downloaded your source code from GitHub, and imported into my project as a module in android studio. And when i encountered the above error, i debugged the code, and the code crashes at line 242 in file ExpandableSelector.java where the app was intended to add the styled buttons.  The error information tells us that we need to set up the layout_width for the widget, aka the buttons, right?  And after looking deep into your sample code, i found out that ExpandableItemStyle has defined the width and height attributes for the buttons added inside Expandable Selector.

That's it.

**Comment by pedrovgs** [comment]
Ok, now I see your point. I'm updating the project readme with information related to this issue. Thank you so much!

**Comment by tyisme614** [comment]
no problem

**Comment by sifendi** [comment]
helllo gaes, i have some problem like this, my result 
Binary XML file line #12: Binary XML file line #30: You must supply a layout_width attribute.

#Needhelp
